"""Table names for shared DraftDNA DB (newsletter_* prefix avoids public.teams collision)."""

TEAMS = "newsletter_teams"
SOURCES = "newsletter_sources"
RAW_ITEMS = "newsletter_raw_items"
STORY_CLUSTERS = "newsletter_story_clusters"
ISSUES = "newsletter_issues"
SECTIONS = "newsletter_sections"
PIPELINE_RUNS = "newsletter_pipeline_runs"
SUBSCRIBERS = "newsletter_subscribers"
GLOSSARY = "newsletter_glossary_terms"

CAMP_PLAYER_SIGNALS = "camp_player_signals"
CAMP_SLOT_SCORES = "camp_slot_scores"
CAMP_BATTLE_PROPOSALS = "camp_battle_proposals"
CAMP_BATTLE_CHANGE_LOG = "camp_battle_change_log"
FANTASY_POSITION_BATTLES = "fantasy_position_battles"
