insert into newsletter_teams (slug, abbrev, name, conference, division, division_order, prev_season_wins, prev_season_losses, prev_season_ties, narrative_tier, reddit_subreddit) values
  ('new-england-patriots', 'ne', 'New England Patriots', 'AFC', 'East', 1, 14, 3, 0, 'elite', 'Patriots'),
  ('buffalo-bills', 'buf', 'Buffalo Bills', 'AFC', 'East', 2, 12, 5, 0, 'contender', 'buffalobills'),
  ('miami-dolphins', 'mia', 'Miami Dolphins', 'AFC', 'East', 3, 7, 10, 0, 'middling', 'miamidolphins'),
  ('new-york-jets', 'nyj', 'New York Jets', 'AFC', 'East', 4, 3, 14, 0, 'rebuilding', 'nyjets'),
  ('pittsburgh-steelers', 'pit', 'Pittsburgh Steelers', 'AFC', 'North', 1, 10, 7, 0, 'contender', 'steelers'),
  ('baltimore-ravens', 'bal', 'Baltimore Ravens', 'AFC', 'North', 2, 8, 9, 0, 'middling', 'ravens'),
  ('cincinnati-bengals', 'cin', 'Cincinnati Bengals', 'AFC', 'North', 3, 6, 11, 0, 'rebuilding', 'bengals'),
  ('cleveland-browns', 'cle', 'Cleveland Browns', 'AFC', 'North', 4, 5, 12, 0, 'rebuilding', 'Browns'),
  ('jacksonville-jaguars', 'jax', 'Jacksonville Jaguars', 'AFC', 'South', 1, 13, 4, 0, 'elite', 'Jaguars'),
  ('houston-texans', 'hou', 'Houston Texans', 'AFC', 'South', 2, 12, 5, 0, 'contender', 'Texans'),
  ('indianapolis-colts', 'ind', 'Indianapolis Colts', 'AFC', 'South', 3, 8, 9, 0, 'middling', 'Colts'),
  ('tennessee-titans', 'ten', 'Tennessee Titans', 'AFC', 'South', 4, 3, 14, 0, 'rebuilding', 'Tennesseetitans'),
  ('denver-broncos', 'den', 'Denver Broncos', 'AFC', 'West', 1, 14, 3, 0, 'elite', 'DenverBroncos'),
  ('los-angeles-chargers', 'lac', 'Los Angeles Chargers', 'AFC', 'West', 2, 11, 6, 0, 'contender', 'Chargers'),
  ('kansas-city-chiefs', 'kc', 'Kansas City Chiefs', 'AFC', 'West', 3, 6, 11, 0, 'rebuilding', 'KansasCityChiefs'),
  ('las-vegas-raiders', 'lv', 'Las Vegas Raiders', 'AFC', 'West', 4, 3, 14, 0, 'rebuilding', 'raiders'),
  ('philadelphia-eagles', 'phi', 'Philadelphia Eagles', 'NFC', 'East', 1, 11, 6, 0, 'contender', 'eagles'),
  ('dallas-cowboys', 'dal', 'Dallas Cowboys', 'NFC', 'East', 2, 7, 9, 1, 'middling', 'cowboys'),
  ('washington-commanders', 'was', 'Washington Commanders', 'NFC', 'East', 3, 5, 12, 0, 'rebuilding', 'Commanders'),
  ('new-york-giants', 'nyg', 'New York Giants', 'NFC', 'East', 4, 4, 13, 0, 'rebuilding', 'NYGiants'),
  ('chicago-bears', 'chi', 'Chicago Bears', 'NFC', 'North', 1, 11, 6, 0, 'contender', 'CHIBears'),
  ('green-bay-packers', 'gb', 'Green Bay Packers', 'NFC', 'North', 2, 9, 7, 1, 'contender', 'GreenBayPackers'),
  ('minnesota-vikings', 'min', 'Minnesota Vikings', 'NFC', 'North', 3, 9, 8, 0, 'middling', 'vikings'),
  ('detroit-lions', 'det', 'Detroit Lions', 'NFC', 'North', 4, 9, 8, 0, 'middling', 'detroitlions'),
  ('carolina-panthers', 'car', 'Carolina Panthers', 'NFC', 'South', 1, 8, 9, 0, 'middling', 'panthers'),
  ('tampa-bay-buccaneers', 'tb', 'Tampa Bay Buccaneers', 'NFC', 'South', 2, 8, 9, 0, 'middling', 'buccaneers'),
  ('atlanta-falcons', 'atl', 'Atlanta Falcons', 'NFC', 'South', 3, 8, 9, 0, 'middling', 'falcons'),
  ('new-orleans-saints', 'no', 'New Orleans Saints', 'NFC', 'South', 4, 6, 11, 0, 'rebuilding', 'Saints'),
  ('seattle-seahawks', 'sea', 'Seattle Seahawks', 'NFC', 'West', 1, 14, 3, 0, 'elite', 'Seahawks'),
  ('los-angeles-rams', 'lar', 'Los Angeles Rams', 'NFC', 'West', 2, 12, 5, 0, 'contender', 'LosAngelesRams'),
  ('san-francisco-49ers', 'sf', 'San Francisco 49ers', 'NFC', 'West', 3, 12, 5, 0, 'contender', '49ers'),
  ('arizona-cardinals', 'ari', 'Arizona Cardinals', 'NFC', 'West', 4, 3, 14, 0, 'rebuilding', 'azcardinals')
on conflict (slug) do nothing;
